import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE / "sample_observation.json"
FACTS = HERE / "generated_observation_facts.pl"
RULES = HERE / "source_gate_rules.pl"
REPORT = HERE / "audit_result.json"


def prolog_atom(value: str) -> str:
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def risk_atom(value: str) -> str:
    value = str(value or "").strip().lower()
    if value in {"low", "niska"}:
        return "low"
    if value in {"medium", "srednia", "średnia"}:
        return "medium"
    if value in {"high", "wysoka"}:
        return "high"
    return "unknown"


def load_observation(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    required = [
        "query",
        "expected_document",
        "expected_page",
        "source_candidate",
        "htr_line",
        "audit",
    ]
    missing = [key for key in required if key not in data]
    if missing:
        raise ValueError(f"Brak wymaganych pól w JSON: {', '.join(missing)}")
    return data


def generate_facts(data: dict) -> None:
    query = data["query"]
    document = data["expected_document"]
    page = int(data["expected_page"])
    source = data["source_candidate"]
    htr = data["htr_line"]
    audit = data["audit"]

    score = float(source.get("score", 0.0))
    min_score = float(data.get("min_source_score", 0.5))
    line_no = int(htr.get("line_number", 0))
    alerts = int(audit.get("hallucination_alerts", 0))
    warnings = int(audit.get("page_warnings", 0))
    risk = risk_atom(audit.get("risk"))

    wrong_source = data.get("negative_cases", {}).get("wrong_source", "wrong-document.jpg")

    groups = {
        "min_source_score": [
            f"min_source_score({min_score:.4f}).",
        ],
        "test_case": [
            "test_case(ok).",
            "test_case(no_scan_line).",
            "test_case(wrong_source).",
            "test_case(risky_audit).",
        ],
        "claim_person": [
            f"claim_person(ok, {prolog_atom(query)}).",
            f"claim_person(no_scan_line, {prolog_atom(query)}).",
            f"claim_person(wrong_source, {prolog_atom(query)}).",
            f"claim_person(risky_audit, {prolog_atom(query)}).",
        ],
        "cited_source": [
            f"cited_source(ok, {prolog_atom(document)}, {page}).",
            f"cited_source(no_scan_line, {prolog_atom(document)}, {page}).",
            f"cited_source(wrong_source, {prolog_atom(wrong_source)}, {page}).",
            f"cited_source(risky_audit, {prolog_atom(document)}, {page}).",
        ],
        "source_candidate": [
            f"source_candidate(ok, {prolog_atom(document)}, {page}, {score:.4f}, yes).",
            f"source_candidate(no_scan_line, {prolog_atom(document)}, {page}, {score:.4f}, yes).",
            f"source_candidate(wrong_source, {prolog_atom(document)}, {page}, {score:.4f}, yes).",
            f"source_candidate(risky_audit, {prolog_atom(document)}, {page}, {score:.4f}, yes).",
        ],
        "htr_line": [
            f"htr_line(ok, {prolog_atom(document)}, {page}, {line_no}, {prolog_atom(query)}).",
            f"htr_line(wrong_source, {prolog_atom(document)}, {page}, {line_no}, {prolog_atom(query)}).",
            f"htr_line(risky_audit, {prolog_atom(document)}, {page}, {line_no}, {prolog_atom(query)}).",
        ],
        "audit_risk": [
            f"audit_risk(ok, {risk}).",
            f"audit_risk(no_scan_line, {risk}).",
            f"audit_risk(wrong_source, {risk}).",
            "audit_risk(risky_audit, high).",
        ],
        "hallucination_alerts": [
            f"hallucination_alerts(ok, {alerts}).",
            f"hallucination_alerts(no_scan_line, {alerts}).",
            f"hallucination_alerts(wrong_source, {alerts}).",
            "hallucination_alerts(risky_audit, 1).",
        ],
        "page_warnings": [
            f"page_warnings(ok, {warnings}).",
            f"page_warnings(no_scan_line, {warnings}).",
            f"page_warnings(wrong_source, {warnings}).",
            f"page_warnings(risky_audit, {warnings}).",
        ],
    }

    lines = [
        "% Generated from sample_observation.json by run_snapshot_audit.py.",
        "% Do not edit this file manually; edit the JSON snapshot instead.",
        "",
    ]
    for name, facts in groups.items():
        lines.append(f"% {name}")
        lines.extend(facts)
        lines.append("")
    FACTS.write_text("\n".join(lines), encoding="utf-8")


def find_prolog(explicit: str | None) -> tuple[str, str]:
    if explicit:
        path = Path(explicit)
        if not path.exists():
            raise FileNotFoundError(f"Nie znaleziono Prologa: {explicit}")
        name = path.name.lower()
        if "swipl" in name:
            return "swi", str(path)
        return "gnu", str(path)

    for candidate in ("gprolog", "gprolog.exe"):
        found = shutil.which(candidate)
        if found:
            return "gnu", found

    for candidate in ("swipl", "swipl.exe"):
        found = shutil.which(candidate)
        if found:
            return "swi", found

    common_windows = [
        Path(r"C:\Program Files\GNU-Prolog\bin\gprolog.exe"),
        Path(r"C:\GNU-Prolog\bin\gprolog.exe"),
        Path(r"C:\Program Files\swipl\bin\swipl.exe"),
        Path(r"C:\Program Files\SWI-Prolog\bin\swipl.exe"),
    ]
    for path in common_windows:
        if path.exists():
            if "swipl" in path.name.lower():
                return "swi", str(path)
            return "gnu", str(path)

    raise FileNotFoundError(
        "Nie znaleziono GNU Prolog ani SWI-Prolog. "
        "Podaj ścieżkę parametrem --prolog."
    )


def run_prolog(kind: str, executable: str) -> str:
    env = os.environ.copy()
    env["LINEDIT"] = "gui=no"

    if kind == "swi":
        cmd = [executable, "-q", "-s", str(RULES), "-g", "run_audit", "-t", "halt"]
    else:
        cmd = [
            executable,
            "--consult-file",
            str(RULES),
            "--query-goal",
            "run_audit,halt",
        ]

    proc = subprocess.run(
        cmd,
        cwd=HERE,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode != 0:
        raise RuntimeError(output)
    return output


def compact_case_lines(output: str) -> list[str]:
    return [line.strip() for line in output.splitlines() if line.strip().startswith("CASE ")]


def main() -> int:
    parser = argparse.ArgumentParser(description="Run a Prolog source gate over a saved RAG/HTR snapshot.")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Path to observation JSON.")
    parser.add_argument("--prolog", default=None, help="Path to gprolog/gprolog.exe or swipl/swipl.exe.")
    args = parser.parse_args()

    observation_path = Path(args.input)
    data = load_observation(observation_path)
    generate_facts(data)
    kind, executable = find_prolog(args.prolog)
    output = run_prolog(kind, executable)
    case_lines = compact_case_lines(output)

    REPORT.write_text(
        json.dumps(
            {
                "input": str(observation_path),
                "prolog_kind": kind,
                "prolog_executable": executable,
                "cases": case_lines,
                "raw_output": output,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    source = data["source_candidate"]
    htr = data["htr_line"]
    audit = data["audit"]

    print("RAG snapshot -> Prolog source gate")
    print(f"query: {data['query']}")
    print(f"cited source: {data['expected_document']}, page {data['expected_page']}")
    print(f"retrieval score: {float(source.get('score', 0.0)):.4f}")
    print(f"HTR line {htr.get('line_number')}: {htr.get('text')}")
    print(
        "audit:",
        risk_atom(audit.get("risk")),
        "hallucination_alerts=" + str(audit.get("hallucination_alerts", 0)),
        "page_warnings=" + str(audit.get("page_warnings", 0)),
    )
    print()
    for line in case_lines:
        print(line)
    print()
    print(f"generated: {FACTS.name}")
    print(f"saved: {REPORT.name}")

    expected = {
        "CASE ok: ACCEPT",
        "CASE no_scan_line: REJECT reasons=[missing_scan_line]",
        "CASE wrong_source: REJECT reasons=[missing_or_weak_cited_source, missing_scan_line]",
        "CASE risky_audit: REJECT reasons=[audit_not_clean]",
    }
    if set(case_lines) != expected:
        print("\nUnexpected Prolog decisions.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
